[package]
name = "thunn/profileservice"

version = "1.0.0"

authors = ["loleris"]
description = "ProfileService is a stand-alone ModuleScript that specialises in loading and auto-saving DataStore profiles."

license = "Apache License 2.0"

registry = "https://github.com/UpliftGames/wally-index"
realm = "server"